version: '3.10'

services:
  application:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data

volumes:
  data:
